Hi <?php echo $_['eventOwner']; ?>,<br /><br />
<?php echo $_['speaker']; ?> has accepted your speaker invite for <b><?php echo $_['eventTitle']; ?></b><br /><br />
<b>Agenda</b><br />
<b>What:</b> <?php echo $_['itineraryTitle']; ?><br />
<b>When:</b> <?php echo $_['itineraryStart']; ?> until <?php echo $_['itineraryEnd']; ?><br />
<b>Where:</b> <?php echo $_['itineraryLocation']; ?>
<br /><br />
For more details on this event, please login to your RCG Event Planner account <a href="http://www.rcgevents.com/admin/">http://www.rcgevents.com/admin/</a>.
<br /><br />
Thanks,<br/>
RCG Events Planner<br/>
<a href="mailto:support@rcgevents.com">support@rcgevents.com</a>