Hi <?php echo $_['user']['first_name']?>,<br /><br />

Can't remember your password? Don't worry about it — it happens.<br /><br />

Your username is: <?php echo $_['user']['email']?><br /><br />

Just click this link to reset your password:<br />
<a href="<?php echo $_['activationKeyData']['url']?>webapp/reset_password?user_id=<?php echo $_['user']['userID']?>&key=<?php echo $_['activationKeyData']['key']?>">
<?php echo $_['activationKeyData']['url']?>webapp/reset_password?user_id=<?php echo $_['user']['userID']?>&key=<?php echo $_['activationKeyData']['key']?>
</a>

<br/><br/>
Thanks,<br/>
RCG Events Planner<br/>
<a href="mailto:support@rcgevents.com">support@rcgevents.com</a>